ex15_js-oop
micro-chipset/external-courses pull request #14
Opened 2019-05-06 14:50 UTC by micro-chipset

2019-05-09 16:44 UTC, eugrdn requested changes
в остальном 👍

2019-05-09 16:44 UTC, eugrdn commented on src/ex15_js-oop/Calculator.js
> +Calculator.prototype.__isNumber = function(number) {
не проверяет +-Infinity

2019-05-09 18:34 UTC, micro-chipset commented on src/ex15_js-oop/Calculator.js
> +Calculator.prototype.__isNumber = function(number) {
Поправил проверку учитывающую Infinity

2019-05-10 04:46 UTC, micro-chipset commented on src/ex15_js-oop/Calculator.js
> +Calculator.prototype.__isNumber = function(number) {
Или даже лучше второй вариант проверки.

2019-05-10 10:11 UTC, merged