Library ver 2
micro-chipset/external-courses pull request #15
Opened 2019-05-17 14:53 UTC by micro-chipset

2019-05-22 19:55 UTC, eugrdn commented on src/library/src/utils/callApi.js
> +const urlBooks = 'https://rsu-library-api.herokuapp.com/books';
это лучше объявить в месте вызова функции

2019-05-22 19:56 UTC, eugrdn commented on src/library/src/utils/callApi.js
> +            saveBooks(data);
утилита не знает про книги, у тебя для этого есть колбек используй его

2019-05-22 20:03 UTC, eugrdn requested changes
уже близко, но я не вижу отдельных компонентов, ты просто сгруппировал собрал функции по файлам (Model/view/controller). Посмотри пример с todoMvc

2019-05-22 20:03 UTC, eugrdn commented on src/library/src/views/library.js
> +        let star = document.createElement('i');
я бы вынес эти 4 строки в createStar

2019-05-22 20:03 UTC, eugrdn commented on src/library/src/views/library.js
> +        while (i--) {
используй метод .find

2019-05-22 20:03 UTC, eugrdn commented on src/library/src/views/library.js
> +        // Find the selected element in the array and put its index variable
тоже .find

2019-05-22 20:03 UTC, eugrdn commented on src/library/src/models/Model.js
> +        (item.author.firstName.toLowerCase().indexOf(value) > -1
все что внутри filter в отдельную функцию

2019-05-22 20:03 UTC, eugrdn commented on src/library/src/controllers/library.controller.js
> +filterTop.addEventListener("click", showFilter);
весь DOM во view

2019-05-23 04:03 UTC, micro-chipset commented on src/library/src/utils/callApi.js
> +const urlBooks = 'https://rsu-library-api.herokuapp.com/books';
Перенес к вызову функции

2019-05-23 04:20 UTC, micro-chipset commented on src/library/src/utils/callApi.js
> +            saveBooks(data);
Переделал используя колбек для сохранения книг.

2019-05-23 04:31 UTC, rakotoz commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
А почему ты не используешь стрелочные функции везде?

2019-05-23 04:32 UTC, micro-chipset commented on src/library/src/utils/callApi.js
> +            saveBooks(data);
Переделал используя колбек.

2019-05-23 04:39 UTC, rakotoz commented on src/library/src/views/library.js
> +    if (books.length === 0) {
Тут можно сократить до `!books.length`)

2019-05-23 04:40 UTC, rakotoz commented on src/library/src/views/library.js
>      books.forEach(function (anotherBook) {
А ты уверен, что у тебя всегда будет books хотябы нулевой массив?

2019-05-23 04:45 UTC, micro-chipset commented on src/library/src/views/library.js
>      books.forEach(function (anotherBook) {
Если сервер не ответит и  через fetch не будут получены данные то:
нулевой массив будет он объявлен `let books = [];`
Пользователю будет выдано книги не найдены. В консоли будет: `console.log(`There was a problem with the request: ${error}`);`

2019-05-23 04:48 UTC, rakotoz commented on src/library/src/views/library.js
>      books.forEach(function (anotherBook) {
ОК) Хорошо, если ты гарантируешь наличие нужных данных

2019-05-23 04:49 UTC, micro-chipset commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
Применял где какая была удобна. Хотя иногда специально после переделывал на стрелочные так код выходит короче и менее запутан. Обязательно ли везде использовать стрелочные?

2019-05-23 04:52 UTC, micro-chipset commented on src/library/src/views/library.js
> +        let star = document.createElement('i');
Добавил createStar

2019-05-23 04:53 UTC, rakotoz commented on src/library/src/models/Model.js
> +    let selectorFilterId = document.querySelector(`#${event.target.id}`);
Я бы сменил название переменной, так как это не id а элемент с нужным тебе id

2019-05-23 05:03 UTC, rakotoz commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
Мне просто больше нравится, когда код в одном стиле написан. Но это не обязательно. Можешь и комбинировать, иногда даже должен)

2019-05-23 05:05 UTC, micro-chipset commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
Понял постараюсь на будущее придерживаться одного стиля.

2019-05-23 05:09 UTC, rakotoz commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
Просто это симпатичнее смотрится, что ли. Но каждому нравится свое

2019-05-23 05:11 UTC, micro-chipset commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
Стрелочные тоже больше нравятся просто пока не очень привык применять их.

2019-05-23 05:25 UTC, micro-chipset commented on src/library/src/models/Model.js
> +        (item.author.firstName.toLowerCase().indexOf(value) > -1
Выделил в отдельную функцию.

2019-05-23 05:31 UTC, micro-chipset commented on src/library/src/controllers/library.controller.js
> +filterTop.addEventListener("click", showFilter);
Перенес в view

2019-05-23 05:37 UTC, micro-chipset commented on src/library/src/views/library.js
> +    if (books.length === 0) {
Поправил так короче будет

2019-05-23 05:40 UTC, micro-chipset commented on src/library/src/models/Model.js
> +    let selectorFilterId = document.querySelector(`#${event.target.id}`);
Переименовал

2019-05-23 06:58 UTC, micro-chipset commented on src/library/src/views/library.js
> +        while (i--) {
Заменил цикл на метод findIndex

2019-05-23 06:58 UTC, micro-chipset commented on src/library/src/views/library.js
> +        // Find the selected element in the array and put its index variable
Заменил цикл на метод findIndex

2019-05-23 09:23 UTC, eugrdn commented on src/library/src/models/Model.js
> +function saveBooks(receivedBooks) {
@rakotoz у нас про es6 лекция только будет на след неделе :)

2019-05-28 11:30 UTC, eugrdn requested changes

2019-05-28 11:30 UTC, eugrdn commented on src/library/src/views/library.js
> +        function createBook(anotherBook) {
вынеси все объявленные здесь функции в методы, а то получается они у тебя создаются на каждый render

2019-05-28 11:30 UTC, eugrdn commented on src/library/src/views/library.js
> +        function setId() {
давай эту функцию вынесем в утилиты, поскольку она может быть переиспользована где угодно

2019-05-28 11:30 UTC, eugrdn commented on src/library/src/views/library.js
> +            model.books.push(book);
сделай это через контроллер, чтобы модели не было во view
setId лучше делать именно в методе модели, как и собирать остальные поля в объект

2019-05-28 11:30 UTC, eugrdn commented on src/library/src/views/library.js
> +    function View(model) {
view знает про controller

2019-05-28 11:30 UTC, eugrdn commented on src/library/src/views/library.js
> +            self.renderBooks(model.setFilter(filterElemId));
у тебя одновременно работают фильтр и строка поиска?

2019-05-28 11:39 UTC, micro-chipset commented on src/library/src/views/library.js
> +            self.renderBooks(model.setFilter(filterElemId));
Да работают одновременно

2019-05-28 11:44 UTC, micro-chipset commented on src/library/src/views/library.js
> +        function setId() {
Вынес в утилиты setId

2019-05-28 12:47 UTC, micro-chipset commented on src/library/src/views/library.js
> +        function createBook(anotherBook) {
Вынес в методы.

2019-05-28 15:03 UTC, micro-chipset commented on src/library/src/views/library.js
> +            self.renderBooks(model.setFilter(filterElemId));
Точнее поиск работал после фильтра уже по его данным. Доделал что бы и фильтры учитывали, что введен поисковый запрос.

2019-05-29 06:30 UTC, micro-chipset commented on src/library/src/views/library.js
> +    function View(model) {
Поправил теперь view знает про controller

2019-05-29 06:31 UTC, micro-chipset commented on src/library/src/views/library.js
> +            model.books.push(book);
Поправил теперь view знает про controller

2019-05-29 19:01 UTC, eugrdn requested changes

2019-05-29 19:01 UTC, eugrdn commented on src/library/src/index.js
> +    this.controller = new Controller();
давай создадим model и view, и передадим в контроллер здесь же

2019-05-29 19:01 UTC, eugrdn commented on src/library/src/models/Model.js
> +            isFilter: false,
за что отвечают эти свойства? isFilter, isSearch?

2019-05-29 19:01 UTC, eugrdn commented on src/library/src/models/Model.js
> +        this.books = [];
books это тоже стейт

2019-05-29 19:01 UTC, eugrdn commented on src/library/src/views/library.js
> +    View.prototype.renderBooks = function (books) {
почему это единственная функция в prototype? 🙂

2019-05-29 19:01 UTC, eugrdn commented on src/library/src/views/library.js
> +        var self = this;
излишне

2019-05-29 19:11 UTC, micro-chipset commented on src/library/src/models/Model.js
> +            isFilter: false,
По ним определяется признак использовался ли фильтр или поиск

2019-05-29 19:14 UTC, micro-chipset commented on src/library/src/models/Model.js
> +        this.books = [];
В books раз выгружены книги и потом используется только для добавления новых.

2019-05-29 19:17 UTC, micro-chipset commented on src/library/src/views/library.js
> +    View.prototype.renderBooks = function (books) {
Другие для внутреннего использование и не требуются не где кроме как во view

2019-05-29 19:19 UTC, eugrdn commented on src/library/src/views/library.js
> +    View.prototype.renderBooks = function (books) {
если у тебя свойство объявлено в конструкторе через this, оно будет доступно так же как и свойство объявленное через prototype

2019-05-29 19:20 UTC, eugrdn commented on src/library/src/models/Model.js
> +        this.books = [];
здесь можно оставить только books, без filtered, избавишься от дублирования данных

2019-05-29 19:23 UTC, micro-chipset commented on src/library/src/views/library.js
> +        var self = this;
Убрал var self = this;

2019-05-29 19:49 UTC, micro-chipset commented on src/library/src/views/library.js
> +    View.prototype.renderBooks = function (books) {
Через подчеркивание пометил, что данные методы для внутреннего использования

2019-05-29 20:07 UTC, micro-chipset commented on src/library/src/models/Model.js
> +        this.books = [];
Пробывал так сделать не понравилось поведение:
1) Вводим поисковый запрос получаем выборку
2) щелкаем по фильтрам работает но если щелкнуть бесплатные книги то букс станет пустой и если потом вернутся на все книги то останется так же пустота

А в моем случае будет сохранено отдельно для поиска выборка и если я после бесплатных книг вернусь ко всем то получу одновременно работу и поиска и фильтра

filteredBooksArray: '',
 searchBooksArray: '',
Это не дублирование books а состояния после фильра и поиска. Если первый вариант и задумывался могу убрать filteredBooksArray и searchBooksArray. Добавил их просто решив что так будет правильнее функционал.

2019-05-29 20:12 UTC, micro-chipset commented on src/library/src/index.js
> +    this.controller = new Controller();
Сделал именно так потому что взаимодействие такое: view <-> controller -> model
А если сделать в App
`function App() {
this.model = new Model();
this.view = new View(this.controller);
this.controller = new Controller(this.model, this.view);
}`
this.controller undefined

2019-05-30 09:36 UTC, micro-chipset commented on src/library/src/models/Model.js
> +        this.books = [];
Переделал используя только один массив books и строку поиска

2019-05-30 12:22 UTC, eugrdn commented on src/library/src/models/Model.js
>          return this.calculateSearch(searchBooks);
это и так у тебя есть в функции state (плохое название для функции)

2019-05-30 12:22 UTC, eugrdn commented on src/library/src/models/Model.js
> +            return this.calculateSearch(books);
возвращай занчение в конце функции после применения обоих фильтров

2019-05-30 12:23 UTC, eugrdn commented on src/library/src/models/Model.js
> +            return this.calculateSearch(books);
передавать переменные как аргументы, которые у тебя и так находятся в this, не имеет смысла

2019-05-30 12:29 UTC, micro-chipset commented on src/library/src/models/Model.js
>          return this.calculateSearch(searchBooks);
переименовал

2019-05-30 12:31 UTC, micro-chipset commented on src/library/src/models/Model.js
> +            return this.calculateSearch(books);
Вернул значение в конце и убрал аргументы функции

2019-05-30 13:45 UTC, eugrdn commented on src/library/src/models/Model.js
>          return this.calculateSearch(searchBooks);
searchBooks и  filterBooks больше не нужны

2019-05-30 13:49 UTC, eugrdn commented on src/library/src/views/library.js
> +        this.newBook = {};
не понял зачем ее объявлять здесь, если можно в самой функции и передать аргументом в метод контроллера, и очищать потом не придется

2019-05-30 15:36 UTC, micro-chipset commented on src/library/src/models/Model.js
>          return this.calculateSearch(searchBooks);
Убрал searchBooks и filterBooks

2019-05-30 15:47 UTC, micro-chipset commented on src/library/src/views/library.js
> +        this.newBook = {};
Убрал из конструктора newBook

2019-05-30 16:48 UTC, eugrdn commented on src/library/src/models/Model.js
> +        return this.calculateSearch(this.checkFiltered());
у тебя calculateSearch и так вызывается в checkFiltered 🙃

2019-05-30 17:42 UTC, micro-chipset commented on src/library/src/models/Model.js
> +        return this.calculateSearch(this.checkFiltered());
И правда там забыл убрать в двух местах. Получилась двойная проверка незачем. Удалил лишнее.

2019-05-30 19:04 UTC, merged