Ex2 js basics part2
micro-chipset/external-courses pull request #2
Opened 2019-03-07 17:53 UTC by micro-chipset

2019-03-07 17:55 UTC, aneelia commented on src/ex2_js-basics-part2/task-01.js
> +function determineType(argument) {
ping

2019-03-08 07:51 UTC, micro-chipset commented
Add task-06. Completed ex2_js.

2019-03-09 19:30 UTC, micro-chipset commented
Merge changes with WebPurple/external-courses

2019-03-12 08:32 UTC, micro-chipset commented
Returned file package-lock.json

2019-03-13 14:53 UTC, aneelia commented on src/ex1_js-basics-part1/task.js
> +let x = 10;
чот не уверена что это должно быть здесь

2019-03-13 14:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-01.js
> +module.exports = determineType;
module.exports пишется после объявления функции, в конце файла

2019-03-13 14:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-04.js
> +    let isEqual = true;
1. нужно поддерживать единообразие в коде. если у тебя два варианта ответа - true  или false, ты либо делаешь 2 переменные, либо ни одной
2. let не целесообразно здесь использовать, лучше const, ведь isEqual ты не переопределяешь

2019-03-13 14:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-05.js
> +    function compareNumeric (a, b) {
на реальных проектах лучше промежуточную функцию делать отдельным блоком кода, чтобы можно было переопределять. имею ввиду, compareNumeric вынести на уровень выше. иначе она не будет доступна больше нигде

2019-03-13 14:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-06.js
> +        result = `Число ${number} - составное число`;
шаблонные строки - пушка

2019-03-13 16:02 UTC, k911mipt commented on src/ex2_js-basics-part2/task-03.js
> +        if(typeof(array[i]) === 'number') {
VSCode settings `"editor.formatOnType": true`

2019-03-13 16:10 UTC, k911mipt commented on src/ex2_js-basics-part2/task-01.js
> +module.exports = determineType;
Не согласен. Можно всю функцию описать как `module.exports = (...args) => { /*body*/ }`

2019-03-13 17:27 UTC, micro-chipset commented on src/ex1_js-basics-part1/task.js
> +let x = 10;
Убрал. Он тут был лишний.

2019-03-13 17:28 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-01.js
> +module.exports = determineType;
module.exports отправил в конец все таки все остальные файлы я так и делал. Решил придерживаться единообразия.

2019-03-13 17:28 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-04.js
> +    let isEqual = true;
Решил  переменная мне и правда не к чему она была лишняя. Убрал ее.

2019-03-13 17:29 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-05.js
> +    function compareNumeric (a, b) {
Вынес функцию compareNumeric. В задании даже не задумался, что эту функцию можно и еще где то применять потому и не вынес сразу.

2019-03-13 17:30 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-06.js
> +        result = `Число ${number} - составное число`;
Шаблонные строки на мой взгляд удобнее применять да и читать легче чем делать через конкатенацию строк, потому использовал их.

2019-03-13 17:31 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-03.js
> +        if(typeof(array[i]) === 'number') {
Добавил и прошел по всем файлам автоформатирование в VSCode.

2019-03-13 17:39 UTC, k911mipt requested changes

2019-03-13 17:39 UTC, k911mipt commented on src/ex2_js-basics-part2/task-04.js
> +        for (let j = 0; j < array.length; j++) {
O(n^2) для данной функции многовато...

2019-03-13 17:39 UTC, k911mipt commented on src/ex2_js-basics-part2/task-05.js
> +    array.sort(compareNumeric);
Из пушки по воробьям. Делать целую сортировку для поиска максимума - такое себе

2019-03-13 17:40 UTC, k911mipt commented
Заканчивай баловаться с `push --force`. Дискуссии из-за этого теряют привязку.

2019-03-13 18:07 UTC, micro-chipset commented
push --force не буду делать

2019-03-13 18:15 UTC, micro-chipset commented
А как нибудь можно иначе не делая push --force если хочу сквошить несколько комитов в один?

2019-03-13 18:19 UTC, k911mipt commented
Пока не запушил, сквошь чо вздумается. То что запушил вне рамкок пулл/мерж реквеста, можно сквошить форсом, этого никто ещё не видел и всем побоку, что ты там творишь. То что запушил в рамках ревью, в принципе тоже можно, пока никто не успел откомментить, но вообще нежелательно, так как твою ветку для ревью могут копировать в свою репу и потом для синхронизации вместо fast-forward merge приходится танцевать, что неприятно. А вот откоменченные части перезаливать - крайне дурной тон

2019-03-13 18:33 UTC, micro-chipset commented
Понял учту в следующих. Буду сквошить до пул реквеста.

2019-03-13 18:46 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-04.js
> +        for (let j = 0; j < array.length; j++) {
Переделал на один цикл. И правда слишком усложнил все сначала.

2019-03-13 18:46 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-05.js
> +    array.sort(compareNumeric);
Переделал иначе через цикл. Просто способ с сортировкой первое, что пришло в голову.

2019-03-14 08:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-01.js
> +    switch (typeof (argument)) {
хорошо бы проверку на NaN добавить, это же не число, по сути, хоть и тип number
typeof (argument) - без скобочек принято писать

2019-03-14 08:53 UTC, aneelia commented on src/ex2_js-basics-part2/task-03.js
> +    let countEven = 0;
можно один раз let написать и перечислить через запятую переменные и их значения

2019-03-14 09:38 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-03.js
> +    let countEven = 0;
Сделал в одну строку.

2019-03-14 09:39 UTC, micro-chipset commented on src/ex2_js-basics-part2/task-01.js
> +    switch (typeof (argument)) {
Да проверку на NaN тут не учел. Теперь добавил. typeof тоже убрал скобки они там лишние.

2019-03-14 10:29 UTC, merged