Ex3 js objects part1
micro-chipset/external-courses pull request #3
Opened 2019-03-10 10:38 UTC by micro-chipset

Completed the tasks section ex3_js-objects-part1

2019-03-13 16:30 UTC, k911mipt requested changes

2019-03-13 16:30 UTC, k911mipt commented on src/ex3_js-objects-part1/task-02.js
> +        if ({}.hasOwnProperty.call(object, key)) {
Зачем так сложно? `if (object.hasOwnProperty(key))` будет достаточно

2019-03-13 16:30 UTC, k911mipt commented on src/ex3_js-objects-part1/task-03.js
> +    for (let key in object) {
А точно необходимо перебирать все свойства чтоб выяснить наличие всего лишь одного?

2019-03-13 16:30 UTC, k911mipt commented on src/ex3_js-objects-part1/task-04.js
> +    for (let key in newObject) {
Предлагаю ознакомиться [MDN#Object.prototype.hasOwnProperty()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)

2019-03-13 16:30 UTC, k911mipt commented on src/ex3_js-objects-part1/task-06.js
> +    let clone = {};
потерял прототип

2019-03-13 18:11 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-02.js
> +        if ({}.hasOwnProperty.call(object, key)) {
Поправил на более простой вариант. Тот вариант нагуглил по замечаю линтера на сайте eslint.

2019-03-13 18:11 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-03.js
> +    for (let key in object) {
Можно проще. Просто вернуть результат string in object

2019-03-13 18:11 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-04.js
> +    for (let key in newObject) {
Не знал о таком методе. Он удобнее моего варианта. Переделал с ним.

2019-03-13 18:12 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-06.js
> +    let clone = {};
Убрал фильтр откидывающий прототип.

2019-03-13 18:28 UTC, k911mipt commented on src/ex3_js-objects-part1/task-04.js
> +    let isExists = false;
Мертвая переменная

2019-03-13 18:45 UTC, k911mipt commented on src/ex3_js-objects-part1/task-06.js
> +    let clone = {};
Нет. прототип теряется, а точнее, не копируется при создании `clone = {}`. Для получения прототипа следует использовать `Object.getPrototypeOf(object)`. Вообще из задания не совсем понятно, насколько "глубоко" следует делать копию... Оставлю этот вопрос открытым на рассмотрение вашему тренеру

2019-03-13 18:49 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-06.js
> +    let clone = {};
Тогда пока оставлю так. Потребуется переделаю.

2019-03-13 18:54 UTC, micro-chipset commented on src/ex3_js-objects-part1/task-04.js
> +    let isExists = false;
Убрал неиспользуемую переменную.

2019-03-15 18:08 UTC, micro-chipset commented
Все замечания поправил.

2019-03-19 12:27 UTC, aneelia commented on src/ex3_js-objects-part1/task-06.js
> +    let clone = {};
достаточно того, что есть, пляски с прототипом оставим на будущее

2019-03-19 12:27 UTC, merged